version: "3.9"

services:
  webapp:
    build: ./telegram_bot
    volumes:
     - ./telegram_bot:/django_app
    image: webapp:django_app
    container_name: telegram_bot_web_app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    ports: 
     - 8000:8000
    command: gunicorn telegram_bot.wsgi:application --bind 0.0.0.0:8000
    #command: python manage.py runserver 0.0.0.0:8000
  db:
    volumes:
      - ./data/db:/var/lib/postgresql/data
    image: postgres
    container_name: postgres_django_telegram_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
    ports:
      - 5432:5432
  nginx:
    build: ./nginx
    volumes: 
     - ./telegram_bot:/django_app
    image: nginx:nginx_app
    container_name: nginx_telegram_app_server
    depends_on:
      - webapp
    ports:
     - 80:80