# Generated by Django 4.1 on 2022-11-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0002_alter_triviagame_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviagame',
            name='poll',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_api.poll'),
        ),
    ]
