# Generated by Django 4.1 on 2022-11-13 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0003_triviagame_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviagameinstance',
            name='trivia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_api.triviagame'),
        ),
    ]
