# Generated by Django 4.1 on 2022-11-13 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0004_alter_triviagameinstance_trivia'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviagame',
            name='chat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_api.chat'),
        ),
        migrations.AlterField(
            model_name='triviagameinstance',
            name='trivia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_api.triviagame'),
        ),
    ]
